name: Feature request
description: Suggest an improvement for H.I.L.D.A Multi List
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like H.I.L.D.A to do?
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: What problem would this solve?
